version: 2

# Default configurations
terraform: &terraform
  docker:
    - image: hashicorp/terraform:0.11.3
  working_directory: ~/test/

jobs:
  validate_infrastructure:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: terraform init
          command: terraform init -backend-config=test-backend.conf
      - run:
          name: Validate Terraform configurations
          command: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (terraform validate -check-variables=false "$m" && echo "√ $m") || exit 1 ; done
      - persist_to_workspace:
          root: .
          paths:
            - .terraform # persist this to be able to apply execution plan without running init once more

  plan_infrastructure:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/test/
      - checkout
      - run:
          name: terraform init
          command: terraform init -backend-config=test-backend.conf
      - run:
          name: terraform plan
          command: terraform plan -input=false -out=tfplan -var-file=test.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - tfplan

  apply_infrastructure:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/test/
      - run:
          name: terraform apply
          command: terraform apply -input=false tfplan

master_workflow_filters: &master_workflow_filters
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  test-plan-apply:
    jobs:
      - validate_infrastructure:
          <<: *master_workflow_filters
      - plan_infrastructure:
          requires:
            - validate_infrastructure
      - approve_infrastructure:
          type: approval
          requires:
            - plan_infrastructure
      - apply_infrastructure:
          requires:
            - approve_infrastructure
